<?php

namespace App\Exports;

use Maatwebsite\Excel\Concerns\FromArray;
use Maatwebsite\Excel\Concerns\WithStyles;
use Maatwebsite\Excel\Concerns\WithColumnWidths;
use Maatwebsite\Excel\Concerns\WithTitle;
use PhpOffice\PhpSpreadsheet\Worksheet\Worksheet;
use PhpOffice\PhpSpreadsheet\Style\Alignment;
use PhpOffice\PhpSpreadsheet\Style\Fill;
use PhpOffice\PhpSpreadsheet\Style\Border;

class ReportExport implements FromArray, WithStyles, WithColumnWidths, WithTitle
{
    public function __construct(private array $data) {}

    public function title(): string
    {
        return substr($this->data['title'], 0, 31); // Excel sheet name max 31 chars
    }

    public function array(): array
    {
        $rows    = $this->data['rows'];
        $columns = $this->data['columns']; // [['key' => 'full_name', 'label' => 'Name'], ...]

        $sheet = [];

        // ── Header rows ───────────────────────────────────────────────────────
        $sheet[] = [$this->data['barangay']];
        $sheet[] = [$this->data['title'] . ($this->data['subtitle'] ? ' — ' . $this->data['subtitle'] : '')];
        $sheet[] = ['Generated by: ' . $this->data['generated_by'] . '   |   ' . $this->data['generated_at']];
        if ($this->data['scope_label']) {
            $sheet[] = ['Scope: ' . $this->data['scope_label']];
        }
        $sheet[] = []; // blank row

        // ── Column headers ────────────────────────────────────────────────────
        $sheet[] = array_column($columns, 'label');

        // ── Data rows ─────────────────────────────────────────────────────────
        foreach ($rows as $row) {
            $line = [];
            foreach ($columns as $col) {
                $line[] = $row[$col['key']] ?? '—';
            }
            $sheet[] = $line;
        }

        // ── Notes ─────────────────────────────────────────────────────────────
        if (!empty($this->data['notes'])) {
            $sheet[] = [];
            $sheet[] = ['Notes / Remarks:'];
            $sheet[] = [$this->data['notes']];
        }

        return $sheet;
    }

    public function styles(Worksheet $sheet): array
    {
        $colCount    = count($this->data['columns']);
        $lastColLetter = \PhpOffice\PhpSpreadsheet\Cell\Coordinate::stringFromColumnIndex($colCount ?: 1);
        $hasScope    = !empty($this->data['scope_label']);
        $headerRow   = $hasScope ? 6 : 5; // column headers row index (1-based)

        // Merge info rows across all columns
        for ($r = 1; $r <= ($hasScope ? 4 : 3); $r++) {
            if ($colCount > 1) {
                $sheet->mergeCells("A{$r}:{$lastColLetter}{$r}");
            }
        }

        return [
            // Barangay name — bold, large
            1 => [
                'font'      => ['bold' => true, 'size' => 13],
                'alignment' => ['horizontal' => Alignment::HORIZONTAL_CENTER],
            ],
            // Report title row
            2 => [
                'font'      => ['bold' => true, 'size' => 11],
                'alignment' => ['horizontal' => Alignment::HORIZONTAL_CENTER],
            ],
            // Generated by row
            3 => [
                'font'      => ['size' => 9, 'color' => ['argb' => 'FF888888']],
                'alignment' => ['horizontal' => Alignment::HORIZONTAL_CENTER],
            ],
            // Column header row — dark background white text
            $headerRow => [
                'font'      => ['bold' => true, 'color' => ['argb' => 'FFFFFFFF']],
                'fill'      => [
                    'fillType'   => Fill::FILL_SOLID,
                    'startColor' => ['argb' => 'FF1F2937'],
                ],
                'alignment' => ['horizontal' => Alignment::HORIZONTAL_CENTER],
            ],
        ];
    }

    public function columnWidths(): array
    {
        // Give each column a reasonable default width
        $widths = [];
        foreach ($this->data['columns'] as $i => $col) {
            $letter = \PhpOffice\PhpSpreadsheet\Cell\Coordinate::stringFromColumnIndex($i + 1);
            $widths[$letter] = 22;
        }
        return $widths;
    }
}