<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <style>
        * { box-sizing: border-box; margin: 0; padding: 0; }

        body {
            font-family: DejaVu Sans, Arial, sans-serif;
            font-size: 10px;
            color: #111;
            padding: 24px 28px;
        }

        /* ── Official Header ── */
        .header {
            display: flex;
            align-items: center;
            gap: 14px;
            border-bottom: 2px solid #1f2937;
            padding-bottom: 10px;
            margin-bottom: 14px;
        }
        .header img {
            width: 52px;
            height: 52px;
            object-fit: contain;
        }
        .header-text .barangay {
            font-size: 13px;
            font-weight: bold;
            color: #1f2937;
        }
        .header-text .address {
            font-size: 9px;
            color: #555;
            margin-top: 1px;
        }
        .header-text .report-title {
            font-size: 12px;
            font-weight: bold;
            margin-top: 4px;
            color: #111;
        }
        .header-text .report-subtitle {
            font-size: 9px;
            color: #555;
            margin-top: 1px;
        }

        /* ── Meta row ── */
        .meta {
            display: flex;
            justify-content: space-between;
            font-size: 8.5px;
            color: #666;
            margin-bottom: 12px;
        }

        /* ── Scope badge ── */
        .scope-badge {
            display: inline-block;
            background: #f3f4f6;
            border: 1px solid #d1d5db;
            border-radius: 4px;
            padding: 2px 8px;
            font-size: 8px;
            color: #374151;
            margin-bottom: 10px;
        }

        /* ── Table ── */
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 14px;
        }
        thead tr {
            background-color: #1f2937;
            color: #fff;
        }
        thead th {
            padding: 6px 8px;
            text-align: left;
            font-size: 9px;
            font-weight: bold;
            letter-spacing: 0.03em;
        }
        tbody tr:nth-child(even) {
            background-color: #f9fafb;
        }
        tbody td {
            padding: 5px 8px;
            font-size: 9px;
            border-bottom: 1px solid #e5e7eb;
            color: #222;
        }
        .no-data {
            text-align: center;
            color: #9ca3af;
            padding: 20px;
            font-size: 9px;
        }

        /* ── Row count ── */
        .row-count {
            font-size: 8.5px;
            color: #6b7280;
            margin-bottom: 10px;
            text-align: right;
        }

        /* ── Notes section ── */
        .notes {
            border-top: 1px solid #e5e7eb;
            padding-top: 10px;
            margin-top: 6px;
        }
        .notes-label {
            font-size: 9px;
            font-weight: bold;
            color: #374151;
            margin-bottom: 4px;
        }
        .notes-body {
            font-size: 9px;
            color: #555;
            line-height: 1.5;
            white-space: pre-wrap;
        }

        /* ── Footer ── */
        .footer {
            position: fixed;
            bottom: 0;
            left: 0;
            right: 0;
            padding: 6px 28px;
            border-top: 1px solid #e5e7eb;
            font-size: 8px;
            color: #9ca3af;
            display: flex;
            justify-content: space-between;
        }
    </style>
</head>
<body>

    {{-- ── Official Header ── --}}
    <div class="header">
        <img src="{{ public_path('images/brgylogo.png') }}" alt="Barangay Logo" />
        <div class="header-text">
            <div class="barangay">{{ $barangay }}</div>
            <div class="address">Local Government Unit — Tourism Management System</div>
            <div class="report-title">{{ $title }}</div>
            @if($subtitle)
                <div class="report-subtitle">{{ $subtitle }}</div>
            @endif
        </div>
    </div>

    {{-- ── Meta row ── --}}
    <div class="meta">
        <span>Generated by: <strong>{{ $generated_by }}</strong></span>
        <span>{{ $generated_at }}</span>
    </div>

    {{-- ── Scope badge ── --}}
    @if($scope_label)
        <div class="scope-badge">Scope: {{ $scope_label }}</div>
    @endif

    {{-- ── Row count ── --}}
    <div class="row-count">{{ count($rows) }} record(s)</div>

    {{-- ── Data table ── --}}
    <table>
        <thead>
            <tr>
                <th>#</th>
                @foreach($columns as $col)
                    <th>{{ $col['label'] }}</th>
                @endforeach
            </tr>
        </thead>
        <tbody>
            @forelse($rows as $i => $row)
                <tr>
                    <td>{{ $i + 1 }}</td>
                    @foreach($columns as $col)
                        <td>{{ $row[$col['key']] ?? '—' }}</td>
                    @endforeach
                </tr>
            @empty
                <tr>
                    <td colspan="{{ count($columns) + 1 }}" class="no-data">
                        No data to display.
                    </td>
                </tr>
            @endforelse
        </tbody>
    </table>

    {{-- ── Notes ── --}}
    @if(!empty($notes))
        <div class="notes">
            <div class="notes-label">Notes / Remarks</div>
            <div class="notes-body">{{ $notes }}</div>
        </div>
    @endif

    {{-- ── Page footer ── --}}
    <div class="footer">
        <span>{{ $barangay }} — Tourism Management System</span>
        <span>{{ $generated_at }}</span>
    </div>

</body>
</html>